# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20170305_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rango.TestCategory'),
        ),
        migrations.AlterField(
            model_name='testrundetail',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rango.TestRun'),
        ),
        migrations.AlterField(
            model_name='testrundetail',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rango.Test'),
        ),
    ]
