# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20170306_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'verbose_name_plural': 'Test Categories'},
        ),
        migrations.AlterModelOptions(
            name='testrun',
            options={'verbose_name_plural': 'Test Runs'},
        ),
        migrations.AlterModelOptions(
            name='testrundetail',
            options={'verbose_name_plural': 'Test Run Details'},
        ),
        migrations.AlterField(
            model_name='testrun',
            name='log',
            field=models.TextField(blank=True, verbose_name='log'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(default='Pending', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_version',
            field=models.CharField(blank=True, max_length=10, verbose_name='tests version'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='time_taken',
            field=models.PositiveIntegerField(blank=True, verbose_name='time taken'),
        ),
    ]
