# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20170308_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='log'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='tests version'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='time_taken',
            field=models.DurationField(blank=True, null=True, verbose_name='time taken'),
        ),
    ]
