# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20170308_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='name'),
        ),
    ]
